<div style="text-align: center"><img src="https://telematica.usm.cl/wp-content/themes/telematica-web/assets/img/header-usm.png" height="75"></div>

# Tarea 1 Módulo 1: Cifrado Histórico y Simétrico
### Asignatura: Criptografía y Seguridad de la Información - TEL252 - 2026
#### _Docente y Autor : Berioska Contreras Vargas - berioska.contreras@usm.cl

* Dictionary: tipo de dato que representa una colección desordenada de elementos modificables e indexados, se declara usando `{}` incluyendo valor y llave por cada elemento.

In [1]:
en = {
    'let' :   ['e','t','a','o','i','n','s','r','h','d','l','u','c','m','f','y','w','g','p','b','v','k','x','q','j','z'],
    'occ' :   [21912, 16587, 14810, 14003, 13318, 12666, 11450, 10977, 10795, 7874, 7253, 5246, 4943, 4761, 4200, 3853, 3819, 3693, 3316, 2715, 2019, 1257, 315, 205, 188, 128],
    'frq' :   [0.12702, 0.09056, 0.08167, 0.07507, 0.06966, 0.06749, 0.06327, 0.06094, 0.05987, 0.04253, 0.04025, 0.02782, 0.02758, 0.02406, 0.02360, 0.02228, 0.02015, 0.01974, 0.01929, 0.01492, 0.00978, 0.00772, 0.00153, 0.00150, 0.00095, 0.00074], 
    }
for k,v in en.items():
    print (k,v)

let ['e', 't', 'a', 'o', 'i', 'n', 's', 'r', 'h', 'd', 'l', 'u', 'c', 'm', 'f', 'y', 'w', 'g', 'p', 'b', 'v', 'k', 'x', 'q', 'j', 'z']
occ [21912, 16587, 14810, 14003, 13318, 12666, 11450, 10977, 10795, 7874, 7253, 5246, 4943, 4761, 4200, 3853, 3819, 3693, 3316, 2715, 2019, 1257, 315, 205, 188, 128]
frq [0.12702, 0.09056, 0.08167, 0.07507, 0.06966, 0.06749, 0.06327, 0.06094, 0.05987, 0.04253, 0.04025, 0.02782, 0.02758, 0.02406, 0.0236, 0.02228, 0.02015, 0.01974, 0.01929, 0.01492, 0.00978, 0.00772, 0.00153, 0.0015, 0.00095, 0.00074]


### **Actividad 1**: Desarrolle un código en Python que permita obtener el mensaje original asociado al siguiente texto cifrado. Considere que el alfabeto inglés fue utilizado en esta sustitución utilizando artimética modular. Explique su análisis y presente un código que consolide la distribución estadística definitiva y que permita aplicar directamente el principio de César.

|line|phrase|
|-|-|
|0 |	lmq jckg yecy lmq vmowg yew vcxn smxw yect ctl myewx ikxg mukth ym kyj jyxckhey avkhey ymucxg yew jqt |
|1 | 	yecy kj emu k uctywg mqx avkhey ym iw |
|2 |	cvicyxmjjwj avl mowx yew jwc ktymrkpcywg il jcvy ctg kmgktw |
|3 |	yewl cxw vknw qtawyywxwg ucowj fvclkth kt yew ckx iqy yewl gm tmy vmjw ymqpe ukye yew myewx ucowj |
|4 |	jymxnj scnw vmth bmqxtwlj ctg yewl pcjy jecgmuj mowx yew acpw ma yew jmkv |
|5 |	iqy vknw cvicyxmjjwj yewl avl wtgvmth xwjykth kt yew ekvvj |
|6 |	mtvl yew vcxn vwcfj mqy ma xqyj vknw c vkow gcxy ctg xkjwj ym iw jucvvmuwg il yew ewcowtj |
|7 |    yewt yew akxscswty awwvj cj yemqhe yew vctg kyjwva ecj xkjwt |
|8 |	vcgwt bqthvwj iwvmu gm tmy ctjuwx yew vcxn |
|9 |    smqtycktj pxqpkakwg mowx yew avcyvctgj gm tmy ctjuwx |
|10|	iqy c ukthwg cxxmu dqkpnvl yxkhhwxj cewcg ctg ky jkthj iwyuwwt yew jqt ctg yew wcxye |
|11|	mtw gmwj tmy ntmu ka yew ikxg ecj pmsw gmut axms yew jqt mx xkjwt axms yew jmkv |
|12|	ky wrkjyj iwyuwwt yew yum vknw c avcsw |
|13|	uewt ky ecj jwxwtcgwg yew jnkwj ukye kyj ciqtgctpw |
|14|	yew acykhqwg vcxn vctgj kt yew pxmf |
|15|	lmq axctpkj uctywg qj ym cpekwow yecy owxykpcv avkhey ukyemqy c iwty |
|16|	kt mxgwx ym cxxkow cy yecy ewcowt uewxw uw pmqvg xwjy kt yew vkhey |
|17|	lmq uctywg yew smxtkth ckx akvvwg ukye cxxmuj ctg ukye c sqvykyqgw ma pcxwaxww vcxnj |
|18|	axctpkj ukye wcpe smxtkth jmth lmq kschktwg yecy c twy ma hmvgwt vcxnj avmcywg iwyuwwt yew wcxye ctg yew jnl |
|19|	uw cxw iqxgwtwg axctpkj |
|20|	uw pewxkje mqx skvg xqy mx gwswctmx |
|21|	uw wrcvy mqxjwvowj kt hvmxl bqjy cj yew ymuwxkth hxcjj cjfkxwj |
|22|	yew vmaykwjy ivcgw gmwj tmy jfct iwlmtg yew ekhe fktwj |
|23|	mtvl uewt uw gkw gm uw cpekwow yecy owxykpcv avkhey |
|24|	twowx chckt ukyeewvg il mqx umxvgvl xqyj mx ukvv mqx imgkwj ktekiky mqx jmqvj |



In [2]:
# Escriba aquí su código y markdown
import pandas as pd
parafo = []
linea = []
count = 0
with open("textocifrado.txt") as file:
    for line in file:
        linea.append(count)
        parafo.append(line.strip())
        count+=1
data = {
    "linea":linea[:len(linea)-1],
    "parafo":parafo[:len(parafo)-1]
}
df = pd.DataFrame(data)
frecuencias = []
for letra in en['let']:
    frec = df['parafo'].str.count(letra).sum()
    frecuencias.append(frec)
dict_frec = {
    
    'letra':en['let'],
    'frec':frecuencias
}
df_frecuencias = pd.DataFrame(dict_frec)
letra_frecuente = df_frecuencias['letra'][df_frecuencias['frec'].idxmax()]
print("Letra más frecuente en el texto cifrado:", letra_frecuente)

df_frecuencias_ordenado = df_frecuencias.sort_values(by='frec', ascending=False).reset_index(drop=True)

diccionario_mapeo = {}
for index, row in df_frecuencias_ordenado.iterrows():
    if index < len(en['let']):
        letra_cifrada = row['letra']
        letra_ingles = en['let'][index]
        diccionario_mapeo[letra_cifrada] = letra_ingles


correcciones_manuales = {
    'c': 'a', 'i': 'b', 'p': 'c', 'g': 'd', 'w': 'e', 
    'a': 'f', 'h': 'g', 'e': 'h', 'k': 'i', 'b': 'j', 
    'n': 'k', 'v': 'l', 's': 'm', 't': 'n', 'm': 'o', 
    'f': 'p', 'd': 'q', 'x': 'r', 'j': 's', 'y': 't', 
    'q': 'u', 'o': 'v', 'u': 'w', 'r': 'x', 'l': 'y', 
    'z': 'z'
}

diccionario_mapeo.update(correcciones_manuales)

def descifrar_linea(texto):
    texto_claro = ""
    for caracter in texto:
        if caracter in diccionario_mapeo:
            texto_claro += diccionario_mapeo[caracter]
        else:
            texto_claro += caracter 
    return texto_claro

for linea in df['parafo']:
    print(descifrar_linea(linea))


Letra más frecuente en el texto cifrado: w
you said that you loved the lark more than any other bird owing to its straight flight toward the sun
that is how i wanted our flight to be
albatrosses fly over the sea intoxicated by salt and iodine
they are like unfettered waves playing in the air but they do not lose touch with the other waves
storks make long journeys and they cast shadows over the face of the soil
but like albatrosses they fly endlong resting in the hills
only the lark leaps out of ruts like a live dart and rises to be swallowed by the heavens
then the firmament feels as though the land itself has risen
laden jungles below do not answer the lark
mountains crucified over the flatlands do not answer
but a winged arrow quickly triggers ahead and it sings between the sun and the earth
one does not know if the bird has come down from the sun or risen from the soil
it exists between the two like a flame
when it has serenaded the skies with its abundance
the fatigued lark lands 

* **Congruencia Modular:** Dado que el factor a es un entero positivo, y $a$ $≡$ $r$ $mod$ $m$, queremos demostrar todos los posibles valores de $r$

In [3]:
def check(q,m):
    if d == q*m:
        return bool(1)
    else:
        return bool(0)
r = [-3,3,9,15]
m = 9
for i in range(0,4):
    d = (42-r[i])    
    q = (d//m)
    print(check(q,m)) # verificación de igualdad

True
False
False
True


* **Clases de Equivalencia:** Sea $m = 5$ y $a = 12$, entonces ¿cuáles son los posibles valores de $r$?
* ¿Cuáles serían las clase de equivalencia de $mod$ $7$?

In [4]:
grupo = [-8,-3,2,7,12,17]
A = []
B = [] 
for i in range(0,5 + 1,1):
    A.append(grupo[i])
    B.append(grupo[i-5])
print(A,B)

[-8, -3, 2, 7, 12, 17] [-3, 2, 7, 12, 17, -8]


* **Reducción:** Por convención se seleccionan los los números positivos más pequeños. La idea es reducir o factorizar para hacer más eficiente el cómputo.

In [5]:
# Dado que 81 = 11 * 7 + 4
exp1 = (3**8)
exp2 = (3**4)**2 
print (exp1, int(exp2)) 
print (16%7)

6561 6561
2


* **Homomorfismo:** Sea $f$ $:$ $G → H$, un mapeo desde el grupo $G$ hacia el grupo $H$, siempre que $f$ preserve la operación de $G$.
* **Máximo Común Divisor:** Identifica un valor que divide a ambos factores de entrada y que en criptografía permite permite identificar valores relativamente primos.

In [6]:
import math
factor = 8184
module = 13
num1, num2 = 88, 93
print(((num1%module)*(num2%module)%module))
print((num1 * num2)%module)
print(((num1%module)+(num2%module)%module))
print((num1 + num2)%module)
print(math.gcd(13,9))

7
7
12
12
1


In [7]:
import math
r0=13; r1=9
print (math.gcd(r0,r1))

1


* **Algoritmo de Euclides:** algoritmo histórico para encontrar un valor máximo común divisor (MCD) de dos números enteros. 
* **Algoritmo de Euclides Extendido:** Permite una búsqueda eficiente de factores relativamente primos. También, es muy relevante en criptografía de llave pública.

In [8]:
def gcd(a, b):
    while a != 0:
        a, b = b % a, a
    return b

def eea(r0,r1):
    if r0 == 0:
        return (r1, 0, 1)
    else:
        g, s, t = eea(r1 % r0, r0)
        return (g, t - (r1 // r0) * s, s)

r0, r1 = 13, 9
print(gcd(r0,r1))
print(eea(r0,r1))

1
(1, -2, 3)


### **Actividad 2**: Analice y proponga un código de cifrado por sustitución que satisfaga los requerimientos del algoritmo **ROT47**, explique su lógica. Luego, desarrolle un código complementario de búsqueda exhaustiva que demuestre la debilidad de ROT47, considerando la  siguiente propiedad de consistencia:

<div style="text-align: center"> s = ROT(ROT(s,47),47)</div>

Explique su planteamiento.

## Lógica ROT47

Este código de cifrado funciona de misma forma que el ROT13, rotando la letra en clave de 47 en vez de 13

### Diferencia de ROT13

A diferencia de ROT13, además de la clave, ROT47 funciona en las clave ASCCI, con los caracteres desde 33 a 126. (Desde el 1 al 32 son invisibles, al igual que el 127). Esto nos obliga a usar el mod 94 para estar dentro de ese rango de caracteres

## Código de ejemplo: 

In [9]:
def rot(texto, n ):
    resultado = []
    for x in texto:
        if 33 <= ord(x) <= 126:
            resultado.append(chr(33 + ((ord(x) -33 + n) % 94)))
        else:
            resultado.append(x)
    return ''.join(resultado)

def rot47(texto):
    return rot(texto, 47)

## Búsqueda exhautiva

In [10]:
def busqueda(texto):
    for n in range(94):
        print(f"{n:2d}: {rot(texto,n)}")

In [11]:
texto = "hola"
cifrado= rot47(texto)
print ("Original ->", texto, "Cifrado ->", cifrado)

Original -> hola Cifrado -> 9@=2


In [12]:
busqueda(cifrado)

 0: 9@=2
 1: :A>3
 2: ;B?4
 3: <C@5
 4: =DA6
 5: >EB7
 6: ?FC8
 7: @GD9
 8: AHE:
 9: BIF;
10: CJG<
11: DKH=
12: ELI>
13: FMJ?
14: GNK@
15: HOLA
16: IPMB
17: JQNC
18: KROD
19: LSPE
20: MTQF
21: NURG
22: OVSH
23: PWTI
24: QXUJ
25: RYVK
26: SZWL
27: T[XM
28: U\YN
29: V]ZO
30: W^[P
31: X_\Q
32: Y`]R
33: Za^S
34: [b_T
35: \c`U
36: ]daV
37: ^ebW
38: _fcX
39: `gdY
40: aheZ
41: bif[
42: cjg\
43: dkh]
44: eli^
45: fmj_
46: gnk`
47: hola
48: ipmb
49: jqnc
50: krod
51: lspe
52: mtqf
53: nurg
54: ovsh
55: pwti
56: qxuj
57: ryvk
58: szwl
59: t{xm
60: u|yn
61: v}zo
62: w~{p
63: x!|q
64: y"}r
65: z#~s
66: {$!t
67: |%"u
68: }&#v
69: ~'$w
70: !(%x
71: ")&y
72: #*'z
73: $+({
74: %,)|
75: &-*}
76: '.+~
77: (/,!
78: )0-"
79: *1.#
80: +2/$
81: ,30%
82: -41&
83: .52'
84: /63(
85: 074)
86: 185*
87: 296+
88: 3:7,
89: 4;8-
90: 5<9.
91: 6=:/
92: 7>;0
93: 8?<1


## Debilidad

La debilidad que tiene esta codificación es la misma propiedad que se indica anteriormente
$
s = ROT(ROT(s,47),47)
$
La misma operación de cifrado es la misma de descifrado. Lo que hace que sea trivial el descifrado. Solo es necesario intentar el descifrado con clave 47 y si no funciona no es.

* **Numpy:** es una biblioteca para programación en lenguaje Python que extiende el soporte para arreglos multi-dimensionales y matrices. Además, cuenta con una colección de funciones matemáticas de alto nivel.

<div style="text-align: center">Instalación: $ pip install numpy</div>
<div style="text-align: center"></div>

| Enlace | Descripción | 
| - | - |
| [Numpy](https://numpy.org/install/) | Instalando Numpy |

In [13]:
import numpy as np 
#np.__version__         # verificar versión
a = [0, 1, 2, 3, 4]
a_np = np.array(a)      # creando un arreglo
"""a_np                    # accediendo al arreglo completo
a_np[2]                 # accediendo a un valor específico
a_np[::2]"""               
print (a_np.tolist())     # convirtiendo el arreglo en lista
print (a_np + 10)
print (a_np * 5)

[0, 1, 2, 3, 4]
[10 11 12 13 14]
[ 0  5 10 15 20]


* **Aritmética Modular:** La aritmética modular nos ayuda a realizar un cómputo lineal y reversible en conjuntos finitos.

In [14]:
import numpy as np 
a = [0, 1, 2, 3, 4, 5, 6, 7]
x = [0, 1, 2, 3, 4, 5, 6, 7]
a_np = np.array(a)
x_np = np.array(x)
print ((a_np + x_np) % 8) 
print ((a_np * x_np) % 8)

[0 2 4 6 0 2 4 6]
[0 1 4 1 0 1 4 1]


* **XOR o Exclusive OR:** es una operación lógica que denota una desigualdad, es decir, el resultado es verdadero si los valores son distintos, de otra forma es falso. También, representa una adición módulo 2. En Python el operador `^` ("_caret_") es equivalente al operador XOR, mientras que el símbolo `&` representa al operador lógico AND. 

In [15]:
import numpy as np
a = np.array([[0,0],[1,1]])
x = np.array([[1,0],[0,1]])
print(a ^ x) # bitwise XOR
print(a & x) # bitwise AND

[[1 0]
 [1 0]]
[[0 0]
 [0 1]]


* **Función Phi de Euler o Totient de Euler:** Identifica cuántos números coprimos existen en un campo finito dado. La función Phi(n) es iterativa utilizando una factorización canónica de números primos.

| Enlace | Descripción | 
| - | - |
| [Sage](https://doc.sagemath.org/html/en/thematic_tutorials/numtheory_rsa.html) | Teoría de Números |

In [16]:
from math import gcd
def myeuler(m):
    phi = 0
    for a in range(1,m):
        if (gcd(a,m) == 1): 
            phi += 1
    return phi
Zm = 81
print("Phi(m): ",myeuler(Zm))

Phi(m):  54


* **Cifrado Simétrico:** transformación que actúa sobre una secuencia de bits en texto claro. El cifrado de llave secreta utiliza una misma llave pre-compartida. 

In [17]:
import numpy as np 
k = np.array([1, 2, 3, 4, 5])
m = np.array([2, 4, 6, 8, 10])
y = ((m ^ k) % 2)
print(y)

[1 0 1 0 1]


* **RAND:** función que genera números pseudoaleatorios.

In [18]:
from numpy.random import rand
c = rand(3, 3)
print (c)

[[0.63643599 0.7389599  0.78309053]
 [0.93876933 0.10988569 0.07512949]
 [0.99434667 0.61836357 0.90184267]]


### **Actividad 3**: Analizar el siguiente código adaptado del cifrado de sustitución Affine. Proponga un código de búsqueda exhaustiva que demuestre la debilidad del algoritmo Affine. Explique su planteamiento.

In [19]:
import random, string, math
alpha = string.ascii_letters+string.digits+string.punctuation+' '
def main():
    m = "C++ is an object-oriented programming language. Everything in C++ is associated with classes and objects, along with its attributes and methods. For example: in real life, a car is an object. The car has attributes, such as weight and color, and methods, such as drive and brake. Attributes and methods are basically variables and functions that belongs to the class. These are often referred to as class members. A class is a user-defined data type that we can use in our program, and it works as an object constructor, or a blueprint for creating objects."
    k =  getRandomk() 
    c = encrypt(k, m)
    print(f"El texto cifrado está entre las comillas simples:\n'{c}'")
    
def getkeys(k):
    k1 = k // len(alpha)
    k2 = k % len(alpha)
    return (k1,k2)
 
def encrypt(k, m):
    k1,k2 = getkeys(k)
    ciphertext = ''
    for symbol in m:
        if symbol in alpha:
            symbolIndex = alpha.find(symbol)
            ciphertext += alpha[(symbolIndex *k1 +k2) % len(alpha)]
        else:
            ciphertext += symbol
    return ciphertext

def getRandomk():
    while True:
        k1 = random.randint(2, len(alpha))
        k2 = random.randint(2, len(alpha))
        if math.gcd(k1, len(alpha)) == 1:
            return k1 * len(alpha) + k2

if __name__ == '__main__':
    main()

El texto cifrado está entre las comillas simples:
'M::Xd'X$@Xe>tIc[oe0dI@[IsXu0e%0$&&d@%XZ$@%f$%IEX)vI0([?d@%Xd@XM::Xd'X$''ecd$[IsXLd[?XcZ$''I'X$@sXe>tIc['~X$Ze@%XLd[?Xd['X$[[0d>f[I'X$@sX&I[?es'EX]e0XI1$&uZI!Xd@X0I$ZXZdYI~X$Xc$0Xd'X$@Xe>tIc[EXz?IXc$0X?$'X$[[0d>f[I'~X'fc?X$'XLId%?[X$@sXceZe0~X$@sX&I[?es'~X'fc?X$'Xs0dvIX$@sX>0$JIEXg[[0d>f[I'X$@sX&I[?es'X$0IX>$'dc$ZZ(Xv$0d$>ZI'X$@sXYf@c[de@'X[?$[X>IZe@%'X[eX[?IXcZ$''EXz?I'IX$0IXeY[I@X0IYI00IsX[eX$'XcZ$''X&I&>I0'EXgXcZ$''Xd'X$Xf'I0osIYd@IsXs$[$X[(uIX[?$[XLIXc$@Xf'IXd@Xef0Xu0e%0$&~X$@sXd[XLe0J'X$'X$@Xe>tIc[Xce@'[0fc[e0~Xe0X$X>ZfIu0d@[XYe0Xc0I$[d@%Xe>tIc['E'


In [20]:
# Escriba aquí su código y markdown
#La debilidad del cifrado de sustitucion Affine es que el espacio de claves es muy pequeño, teniendo solo 6840 claves disponibles
import string
import math

alpha = string.ascii_letters+string.digits+string.punctuation+' '#Tenemos 95 posibles caracteres
m = len(alpha) 


def decrypt(a, b, ciphertext):
    # Inverso multiplicativo de a modulo m
    a_inv = pow(a, -1, m)

    plaintext = ''

    for symbol in ciphertext:
        if symbol in alpha:
            c = alpha.find(symbol)

            # x = a^(-1)(c-b) mod m
            x = (a_inv * (c - b)) % m

            plaintext += alpha[x]
        else:
            plaintext += symbol

    return plaintext


def brute_force(ciphertext):
    candidates = []

    for a in range(m):
        # Las claves para affine requieren cumplir que  gcd(a,m)=1
        if math.gcd(a, m) != 1:
            continue

        for b in range(m):
            plaintext = decrypt(a, b, ciphertext)

            candidates.append((a, b, plaintext))

    return candidates


import datetime

def main():
    ciphertext = input("Ingrese el texto cifrado: ")
    keyword = input("Ingrese una palabra para filtrar (Enter para guardar todos en un txt): ").strip().upper()

    candidates = brute_force(ciphertext)

    if keyword:
        matches = [c for c in candidates if keyword in c[2].upper()]
        
        print("\n" + "="*50)
        print(f"Claves totales probadas: {len(candidates)}")
        print(f"Coincidencias mostradas: {len(matches)}")
        print("="*50 + "\n")

        for a, b, plaintext in matches:
            print(f"[a={a:2d}, b={b:2d}] -> {plaintext}")
            
        if not matches:
            print("No se encontraron resultados con esa palabra clave.")
            
    else:
        fecha_actual = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        nombre_archivo = f"affine_{fecha_actual}.txt"
        
        try:
            with open(nombre_archivo, "w", encoding="utf-8") as file:
                file.write(f"Texto cifrado original: {ciphertext}\n")
                file.write(f"Claves probadas: {len(candidates)}\n")
                file.write("="*50 + "\n")
                
                for a, b, plaintext in candidates:
                    file.write(f"[a={a:2d}, b={b:2d}] -> {plaintext}\n")
                    
            print(f"\n[+] Éxito: Se han guardado {len(candidates)} combinaciones en '{nombre_archivo}'")
            
        except IOError as e:
            print(f"\n[-] Error al intentar guardar el archivo: {e}")

if __name__ == '__main__':
    main()

Ingrese el texto cifrado:  M::Xd'X$@Xe>tIc[oe0dI@[IsXu0e%0$&&d@%XZ$@%f$%IEX)vI0([?d@%Xd@XM::Xd'X$''ecd$[IsXLd[?XcZ$''I'X$@sXe>tIc['~X$Ze@%XLd[?Xd['X$[[0d>f[I'X$@sX&I[?es'EX]e0XI1$&uZI!Xd@X0I$ZXZdYI~X$Xc$0Xd'X$@Xe>tIc[EXz?IXc$0X?$'X$[[0d>f[I'~X'fc?X$'XLId%?[X$@sXceZe0~X$@sX&I[?es'~X'fc?X$'Xs0dvIX$@sX>0$JIEXg[[0d>f[I'X$@sX&I[?es'X$0IX>$'dc$ZZ(Xv$0d$>ZI'X$@sXYf@c[de@'X[?$[X>IZe@%'X[eX[?IXcZ$''EXz?I'IX$0IXeY[I@X0IYI00IsX[eX$'XcZ$''X&I&>I0'EXgXcZ$''Xd'X$Xf'I0osIYd@IsXs$[$X[(uIX[?$[XLIXc$@Xf'IXd@Xef0Xu0e%0$&~X$@sXd[XLe0J'X$'X$@Xe>tIc[Xce@'[0fc[e0~Xe0X$X>ZfIu0d@[XYe0Xc0I$[d@%Xe>tIc['E
Ingrese una palabra para filtrar (Enter para guardar todos en un txt):  



[+] Éxito: Se han guardado 6840 combinaciones en 'affine_20260826_231711.txt'


* **One Time Pad:** De acuerdo a Claude Shannon, al menos tres son los principios que permiten otorgar un secreto perfecto. Uno de ellos es una llave impredecible.

In [21]:
import string
import secrets as prng
a = prng.randbelow(25) # función más robusta que rand
#print (a)
b = prng.choice(string.ascii_letters)
#print(b)
c = prng.choice(['apruebo','rechazo','nulo','blanco'])
print(c)

nulo


* **Módulo Secrets:** Genera números aleatorios de manera segura para gestión de secretos. Es próximo a un generador criptográfico y más seguro que el módulo random.

In [22]:
import string, secrets as prng
ps = ''
for i in range(13):
    ps+=prng.choice(string.ascii_letters)
print (ps)

QlciyXDuPVfTs


* **Módulo Secrets:** Generar una contraseña alfanumérica de N caracteres de longitud.

In [23]:
import string, secrets
alphabet = string.ascii_letters + string.digits
password = ''.join(secrets.choice(alphabet) for i in range(16))
print(password)

iljyTU8LUzdwCLqu


* **Proyecto PyLFSR:** Proyecto que propone una función generadora de registros de desplazamiento de retroalimentación lineal, y perfectible. 

| Enlace | Descripción | 
| - | - |
| [PyLFSR](https://pypi.org/project/pylfsr/) | LFSR en Python |

In [24]:
%pip install pylfsr

Note: you may need to restart the kernel to use updated packages.


In [25]:
# Ejemplo: Polinomio primitivo por omisión x^5 + x^2 + 1
import numpy as np
from pylfsr import LFSR
L = LFSR()
L.info()  
L.runFullCycle()

5-bit LFSR with feedback polynomial  x^5 + x^2 + 1 with
Expected Period (if polynomial is primitive) =  31
Computing configuration is set to Fibonacci with output sequence taken from 5-th (-1) register
Current :
 State        :  [1 1 1 1 1]
 Count        :  0
 Output bit   :  -1
 feedback bit :  -1


/tmp/ipykernel_588837/3469261419.py:6: DeprecationWarning: function runFullCycle will be deprecated in future version, due to misnomer, use "runFullPeriod" instead.
  L.runFullCycle()


array([1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0])

In [26]:
# Ejemplo: Polinomio primitivo propuesto x^4 + x + 1
import numpy as np
from pylfsr import LFSR
semilla = [1,0,0,0,0,0,1]
polinomio = [7,1]
L = LFSR(fpoly=polinomio,initstate =semilla, verbose=True)
L.info()
#L.runKCycle(10)
L.runFullCycle()

7-bit LFSR with feedback polynomial  x^7 + x^1 + 1 with
Expected Period (if polynomial is primitive) =  127
Computing configuration is set to Fibonacci with output sequence taken from 7-th (-1) register
Current :
 State        :  [1 0 0 0 0 0 1]
 Count        :  0
 Output bit   :  -1
 feedback bit :  -1
S:  [1 0 0 0 0 0 1]
S:  [0 1 0 0 0 0 0]
S:  [0 0 1 0 0 0 0]
S:  [0 0 0 1 0 0 0]
S:  [0 0 0 0 1 0 0]
S:  [0 0 0 0 0 1 0]
S:  [0 0 0 0 0 0 1]
S:  [1 0 0 0 0 0 0]
S:  [1 1 0 0 0 0 0]
S:  [1 1 1 0 0 0 0]
S:  [1 1 1 1 0 0 0]
S:  [1 1 1 1 1 0 0]
S:  [1 1 1 1 1 1 0]
S:  [1 1 1 1 1 1 1]
S:  [0 1 1 1 1 1 1]
S:  [1 0 1 1 1 1 1]
S:  [0 1 0 1 1 1 1]
S:  [1 0 1 0 1 1 1]
S:  [0 1 0 1 0 1 1]
S:  [1 0 1 0 1 0 1]
S:  [0 1 0 1 0 1 0]
S:  [0 0 1 0 1 0 1]
S:  [1 0 0 1 0 1 0]
S:  [1 1 0 0 1 0 1]
S:  [0 1 1 0 0 1 0]
S:  [0 0 1 1 0 0 1]
S:  [1 0 0 1 1 0 0]
S:  [1 1 0 0 1 1 0]
S:  [1 1 1 0 0 1 1]
S:  [0 1 1 1 0 0 1]
S:  [1 0 1 1 1 0 0]
S:  [1 1 0 1 1 1 0]
S:  [1 1 1 0 1 1 1]
S:  [0 1 1 1 0 1 1]
S:  [1 0 1 1 1 

/tmp/ipykernel_588837/3802484739.py:9: DeprecationWarning: function runFullCycle will be deprecated in future version, due to misnomer, use "runFullPeriod" instead.
  L.runFullCycle()


array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1])

In [27]:
# Ejemplo: Listar polinomios primitivos conocidos
L = LFSR()
fpolyDict = L.get_fpolyList(m=2)
print (fpolyDict)
fpolyDict = L.get_fpolyList()
print (fpolyDict)

[[2, 1]]
{2: [[2, 1]], 3: [[3, 1]], 4: [[4, 1]], 5: [[5, 2], [5, 4, 2, 1], [5, 4, 3, 2]], 6: [[6, 1], [6, 5, 2, 1], [6, 5, 3, 2]], 7: [[7, 1], [7, 3], [7, 3, 2, 1], [7, 4, 3, 2], [7, 5, 4, 3, 2, 1], [7, 6, 3, 1], [7, 6, 4, 2], [7, 6, 5, 2], [7, 6, 5, 4, 2, 1]], 8: [[8, 4, 3, 2], [8, 5, 3, 1], [8, 6, 4, 3, 2, 1], [8, 6, 5, 1], [8, 6, 5, 2], [8, 6, 5, 3], [8, 7, 6, 1], [8, 7, 6, 5, 2, 1]], 9: [[9, 4], [9, 5, 3, 2], [9, 6, 4, 3], [9, 6, 5, 3, 2, 1], [9, 6, 5, 4, 2, 1], [9, 7, 6, 4, 3, 1], [9, 8, 4, 1], [9, 8, 5, 4], [9, 8, 6, 5], [9, 8, 6, 5, 3, 1], [9, 8, 7, 2], [9, 8, 7, 3, 2, 1], [9, 8, 7, 6, 5, 1], [9, 8, 7, 6, 5, 3]], 10: [[10, 3], [10, 4, 3, 1], [10, 6, 5, 3, 2, 1], [10, 8, 3, 2], [10, 8, 4, 3], [10, 8, 5, 1], [10, 8, 5, 4], [10, 8, 7, 6, 5, 2], [10, 8, 7, 6, 5, 4, 3, 1], [10, 9, 4, 1], [10, 9, 6, 5, 4, 3, 2, 1], [10, 9, 8, 6, 3, 2], [10, 9, 8, 6, 5, 1], [10, 9, 8, 7, 6, 5, 4, 3]], 11: [[11, 2], [11, 5, 3, 1], [11, 5, 3, 2], [11, 6, 5, 1], [11, 7, 3, 2], [11, 8, 5, 2], [11, 8, 6, 5,

* **Múltiples Generadores:** El sistema global de comunicaciones móviles GSM utiliza encriptación de llamadas utilizando la familia de algoritmos A5. El algoritmo A5/1 es un cifrado simétrico por flujos A5/1. Inicialmente A5/1 fue un algoritmo secreto que con el tiempo demostró debilidades. Dentro de las propuestas de mejoramimento, se encuentran la modificación del polinomio del LFSR, y el uso aleatorio de múltiples registros LFSR. Tiempo después, la versión A5/2 demostró imperfecciones, quedando rápidamente obsoleta. En el año 2007, se define como nuevo estándar para las redes 3GPP al algoritmo A5/3 Kasumi, cifrado simétrico por bloques. 

| Enlace | Descripción | 
| - | - |
| [IEEE](https://doi.org/10.1109/ETNCC.2011.5958486) | Enhancement of A5/1 |
| [3GPP Security](https://portal.3gpp.org/desktopmodules/Specifications/SpecificationDetails.aspx?specificationId=2387) | Kasumi Specification |


In [28]:
# Múltiples generadores LFSR inicializados
R1 = LFSR(fpoly = [19,18,17,14])
R2 = LFSR(fpoly = [23,22,21,8])
R3 = LFSR(fpoly = [22,21])

# Bits de reloj
b1 = R1.state[8]
b2 = R1.state[10]
b3 = R1.state[10]

### **Actividad 4**: Construir un registro de desplazamiento de retroalimentación lineal eficiente para un campo finito binario, que cumpla con:
- Utilizar un polinomio primitivo de grado mayor a 20.
- Demuestre que la llave de flujo es consistente con el periodo máximo.
- No es posible invocar funciones LFSR preexistentes p.e. PyLFSR.

In [29]:
import secrets

In [30]:
grado = 21
max_val = 2**(grado-1)

llave_inicial = secrets.randbelow(max_val) + 1 # Para evitar el 0
polinomio = (1 << 0) | (1 << 2)  # (0,1,21)

print(f"Llave inicial: {llave_inicial}")
for i in range(grado-1,-1, -1):
    print((llave_inicial>>i)&1, end="")
print("\n")
print(f"Polinomio: {polinomio}")
for i in range(grado-1,-1,-1):
    print((polinomio>>i)&1, end="")

#Cheat sheet de operaciones bitwise:
#>> shift derecho
#<< shift izquierdo
#& AND
#^ XOR

# Inicializar variable de salida
output = llave_inicial&1
registros = llave_inicial
clock_cycle = 0

def calcular_output():
    global clock_cycle
    global polinomio
    global registros
    global output
    
    if clock_cycle == 0:
        clock_cycle+=1
        return output
    else:
        suma = output&(polinomio&1)
        for j in range(0,grado):
            polinomio_j = (polinomio>>j)&1
            registro_j = (registros>>j)&1
            suma ^= polinomio_j&registro_j
        registros >>= 1
        registros = registros | (suma << (grado-1))
        clock_cycle+=1
        return(registros&1)

def imprimir_registros_polinomio():
    global grado
    global registros
    global polinomio

    print(f"Registros: ", end="")
    for i in range(grado-1,-1,-1):
        print((registros>>i)&1, end="")
    print(", ",end="")
    print(f"Polinomio: ", end="")
    for i in range(grado-1,-1,-1):
        print((polinomio>>i)&1, end="")
    print("")

Llave inicial: 308309
001001011010001010101

Polinomio: 5
000000000000000000101

In [31]:
# --- INICIO DEL CHECK DE LONGITUD MÁXIMA ---
#Nota: La implementación de las funciones del bloque anterior fueron hechas 100% por humanos.
# el único aporte de la IA fueron para el código a continuación, así como para consolidar y aprender los conceptos necesarios, como el manejo
# de las operaciones bitwise, y comprensión del texto Understanding Cryptography - Cristof Paar, Jan Pelzl.

print("-" * 30)
print("Iniciando check de periodo...")

periodo_teorico = (2 ** grado) - 1
ciclos_reales = 0

# Guardamos el objetivo
estado_objetivo = llave_inicial

while True:
    calcular_output()
    #imprimir_registros_polinomio()
    
    # Tu función calcular_output() no altera 'registros' en clock_cycle == 0,
    # por lo que empezamos a contar y verificar a partir del ciclo 1.
    if clock_cycle > 1:
        ciclos_reales += 1
        
        # Si el registro vuelve a la llave inicial, completamos el ciclo
        if registros == estado_objetivo:
            break
            
        # Freno de emergencia: Si supera el periodo teórico, 
        # significa que entró en un sub-ciclo y nunca volverá a la llave inicial.
        if ciclos_reales > periodo_teorico:
            break

print(f"Periodo alcanzado : {ciclos_reales}")
print(f"Periodo máximo teórico : {periodo_teorico}")

if ciclos_reales == periodo_teorico:
    print("✅ ¡ÉXITO! El LFSR alcanzó la longitud máxima.")
    print("   (El polinomio generado ES PRIMITIVO).")
else:
    print("❌ NO alcanzó la longitud máxima.")
    print("   (El polinomio generado NO es primitivo o el estado se atascó).")

------------------------------
Iniciando check de periodo...
Periodo alcanzado : 2097151
Periodo máximo teórico : 2097151
✅ ¡ÉXITO! El LFSR alcanzó la longitud máxima.
   (El polinomio generado ES PRIMITIVO).


### Fin de la Tarea!!!